FROM tensorflow/tensorflow:1.13.0

RUN mkdir -p /data
VOLUME /data

WORKDIR /data

RUN pip install --upgrade pip
RUN python -m pip install jupyterlab gputil psutil humanize seaborn keras tables nltk faker tqdm babel gensim 
    

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]
